# /nginx/nginx.conf /etc/nginx/conf.d
version: "3"

services:
  # nginx:
  #   image: nginx:latest
  #   container_name: webserver
  #   restart: unless-stopped
  #   ports:
  #     - 8080:80
  #     # - 443:443
  #   volumes:
  #     - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #   network_mode: "host"

  rabbitmq:
    image: rabbitmq:management
    restart: always
    container_name: rabbitmq
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    ports:
      - 5672:5672
      - 8099:15672

  # users-services:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile-node
  #   image: ${PROJECT_NAME}-node
  #   container_name: ${PROJECT_NAME}-node-${NODE_ENV}
  #   expose:
  #     - "9000"

volumes:
  rabbitmq_data:
